// Playback for the generated narration, per BUILD-SPEC-v2.md §13.
//
// The audio is 552 files, one per printed block, generated by scripts/audio.mjs. That shape is
// what makes this component simple: a section is a file, so "skip this section" is "play the next
// file" and there is no seeking, no chapter table, and nothing that can drift out of sync.
//
// What §13 asks for and where it lives here:
//   - two tracks, description then interpretation. Only interpretation exists as content, so only
//     interpretation plays. See docs/audio-generation.md for what was cut and why.
//   - variable speed 0.5x-2x, pitch preserved. RATES below; preservesPitch is set on the element.
//   - plays across navigation. The element is created once, outside React's tree, and the provider
//     sits above the router - so changing page does not interrupt the narration.
//   - cues map one-to-one onto printed segments, generated at production time. We only read them.

import { createContext, useCallback, useContext, useEffect, useRef, useState } from 'react'
import { useT } from './lang.jsx'
import { useA11y } from './a11y.jsx'

const BASE = '/audio/en'
export const RATES = [0.5, 0.75, 1, 1.25, 1.5, 2]

// The printed blocks of one segment, built exactly the way scripts/audio.mjs builds them. If these
// two ever disagree the cue text stops lining up with the words on screen, so the construction is
// deliberately identical rather than merely similar.
export const blocksOf = (heading, text) =>
  [heading, ...String(text ?? '').split(/\n{2,}/)].map((b) => (b ?? '').trim()).filter(Boolean)

// ------------------------------------------------------------------ cues

const toSeconds = (t) => {
  const [h, m, s] = t.split(':')
  return Number(h) * 3600 + Number(m) * 60 + Number(s)
}

function parseVtt(text) {
  const out = []
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(/^(\d\d:\d\d:\d\d\.\d\d\d) --> (\d\d:\d\d:\d\d\.\d\d\d)/)
    if (!m) continue
    const body = (lines[i + 1] ?? '').trim()
    if (body) out.push({ start: toSeconds(m[1]), end: toSeconds(m[2]), text: body })
  }
  return out
}

// Turn each cue into a character range inside one of the printed blocks, so the page can highlight
// the actual rendered text rather than a copy of it.
//
// This walks forwards and never searches backwards: the narration reads the blocks in order, so a
// cue is always at or after the previous one. That matters for repeated words - highlighting the
// first "the" in a paragraph every time the voice says "the" would look broken, and a naive
// indexOf from zero would do exactly that.
function alignCues(cues, blocks) {
  const out = []
  let b = 0
  let pos = 0
  for (const cue of cues) {
    const needle = cue.text.trim()
    if (!needle) continue
    let placed = false
    while (b < blocks.length) {
      const at = blocks[b].indexOf(needle, pos)
      if (at !== -1) {
        out.push({ ...cue, block: b, from: at, to: at + needle.length })
        pos = at + needle.length
        placed = true
        break
      }
      b++
      pos = 0
    }
    // A cue we cannot place means the text on screen is not the text that was voiced. Rather than
    // highlight the wrong words, stop aligning and let the rest play without a highlight.
    if (!placed) break
  }
  return out
}

// ------------------------------------------------------------------ provider

const Ctx = createContext(null)
export const useAudio = () => useContext(Ctx)

export function AudioProvider({ children }) {
  const el = useRef(null)
  if (el.current === null && typeof Audio !== 'undefined') {
    el.current = new Audio()
    el.current.preload = 'none'
  }

  // queue: { key, title, items: [{ id, label, blocks }] }. key identifies what is playing so a
  // second press on the same thing toggles rather than restarts.
  const [queue, setQueue] = useState(null)
  const [at, setAt] = useState(0)
  const [playing, setPlaying] = useState(false)
  const [rate, setRateRaw] = useState(1)
  const [cues, setCues] = useState([])
  const [cue, setCue] = useState(-1)
  const [time, setTime] = useState(0)
  const [duration, setDuration] = useState(0)
  const [failed, setFailed] = useState(false)

  // Read-along only works if the highlighted word is on screen, and until now nothing kept it
  // there — the narration ran on while the visitor sat looking at a paragraph it had left. On by
  // default because following the words is the whole point of §13's one-to-one cue mapping;
  // switchable, because auto-scroll fights anyone who wants to read ahead or back. The switch is
  // in Display settings (§18) rather than the player: it is a preference, and it should persist.
  const { prefs } = useA11y()
  const follow = prefs.followWords
  const [t] = useT()

  const item = queue?.items[at] ?? null

  // Load the segment whenever the queue or position changes. `wanted` guards against a fast
  // sequence of skips resolving out of order and leaving stale cues on screen.
  useEffect(() => {
    const audio = el.current
    if (!audio || !item) return
    let wanted = true
    setCues([])
    setCue(-1)
    setFailed(false)
    audio.src = `${BASE}/${item.id}.mp3`
    audio.playbackRate = rate
    audio.preservesPitch = true
    if (playing) audio.play().catch(() => setFailed(true))

    fetch(`${BASE}/${item.id}.vtt`)
      .then((r) => (r.ok ? r.text() : Promise.reject(new Error(String(r.status)))))
      .then((text) => {
        if (wanted) setCues(alignCues(parseVtt(text), item.blocks))
      })
      // No cues is a degraded but working player: audio plays, nothing highlights.
      .catch(() => {})

    return () => {
      wanted = false
    }
    // `playing` and `rate` are deliberately not dependencies - they are applied here on load and
    // maintained by the effects below. Including them would reload the file on every speed change.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [item?.id])

  useEffect(() => {
    const audio = el.current
    if (!audio) return
    audio.playbackRate = rate
    audio.preservesPitch = true
  }, [rate])

  // Follow the playhead on animation frames rather than the element's timeupdate event, which
  // fires about four times a second - fine for a progress bar, visibly late for a word.
  useEffect(() => {
    const audio = el.current
    if (!audio || !playing) return
    let raf = 0
    const tick = () => {
      const now = audio.currentTime
      setTime(now)
      setCue((prev) => {
        if (cues[prev] && now >= cues[prev].start && now < cues[prev].end) return prev
        const next = cues.findIndex((c) => now >= c.start && now < c.end)
        return next
      })
      raf = requestAnimationFrame(tick)
    }
    raf = requestAnimationFrame(tick)
    return () => cancelAnimationFrame(raf)
  }, [playing, cues])

  useEffect(() => {
    const audio = el.current
    if (!audio) return
    const onEnd = () => {
      setAt((i) => {
        if (!queue || i + 1 >= queue.items.length) {
          setPlaying(false)
          return i
        }
        return i + 1
      })
    }
    const onMeta = () => setDuration(audio.duration || 0)
    const onErr = () => setFailed(true)
    audio.addEventListener('ended', onEnd)
    audio.addEventListener('loadedmetadata', onMeta)
    audio.addEventListener('error', onErr)
    return () => {
      audio.removeEventListener('ended', onEnd)
      audio.removeEventListener('loadedmetadata', onMeta)
      audio.removeEventListener('error', onErr)
    }
  }, [queue])

  const start = useCallback(
    (next, from = 0) => {
      const audio = el.current
      if (!audio) return
      if (queue?.key === next.key) {
        // Same thing already loaded: treat the press as play/pause.
        if (playing) {
          audio.pause()
          setPlaying(false)
        } else {
          audio.play().catch(() => setFailed(true))
          setPlaying(true)
        }
        return
      }
      setQueue(next)
      setAt(from)
      setPlaying(true)
    },
    [queue, playing]
  )

  const toggle = useCallback(() => {
    const audio = el.current
    if (!audio || !queue) return
    if (playing) {
      audio.pause()
      setPlaying(false)
    } else {
      audio.play().catch(() => setFailed(true))
      setPlaying(true)
    }
  }, [queue, playing])

  // §13's skip. Because a section is a file, this is just "load the next one" - it cannot land in
  // the wrong place the way a seek into a long file can.
  const skip = useCallback(
    (delta) => {
      if (!queue) return
      setAt((i) => Math.min(queue.items.length - 1, Math.max(0, i + delta)))
      setPlaying(true)
    },
    [queue]
  )

  const stop = useCallback(() => {
    const audio = el.current
    if (audio) {
      audio.pause()
      audio.removeAttribute('src')
      audio.load()
    }
    setQueue(null)
    setPlaying(false)
    setCues([])
    setCue(-1)
  }, [])

  const setRate = useCallback((r) => setRateRaw(r), [])

  const seek = useCallback((seconds) => {
    const audio = el.current
    if (!audio || !Number.isFinite(seconds)) return
    audio.currentTime = seconds
    setTime(seconds)
  }, [])

  // Keep the spoken word on screen. Runs after the cue has rendered, so the <mark> exists.
  //
  // Only scrolls when the word has actually left the viewport — scrolling on every cue would
  // twitch the page several times a second. The bottom margin clears the player, which is fixed
  // over the end of the page.
  useEffect(() => {
    if (!follow || !playing) return
    const mark = document.querySelector('.spoken-word')
    if (!mark) return
    const r = mark.getBoundingClientRect()
    const bar = document.querySelector('.audio-bar')?.getBoundingClientRect().height ?? 0
    const top = 72
    const bottom = innerHeight - bar - 24
    if (r.top >= top && r.bottom <= bottom) return
    // §18 asks for prefers-reduced-motion on every transition. A smooth scroll that repeats for
    // 137 minutes is exactly what that setting is for.
    const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches
    mark.scrollIntoView({ block: 'center', behavior: reduced ? 'auto' : 'smooth' })
  }, [cue, follow, playing])

  // Lock screen, headphone buttons, car displays. A visitor walking a gallery with the phone in a
  // pocket is the case §13's "plays across navigation" is really about, and without this the only
  // way to pause is to take the phone out and find the bar.
  useEffect(() => {
    if (!('mediaSession' in navigator)) return
    if (!queue || !item) {
      navigator.mediaSession.metadata = null
      navigator.mediaSession.playbackState = 'none'
      return
    }
    navigator.mediaSession.metadata = new MediaMetadata({
      title: item.label,
      // For a single object the queue title and the first item's label are the same string, and a
      // lock screen showing the same words twice reads as a bug.
      artist: queue.title === item.label ? t('ui.collectionTitle') : queue.title,
      album: 'Canterbury Museum',
    })
    navigator.mediaSession.playbackState = playing ? 'playing' : 'paused'
  }, [queue, item, playing, t])

  useEffect(() => {
    if (!('mediaSession' in navigator)) return
    const handlers = {
      play: () => toggle(),
      pause: () => toggle(),
      previoustrack: () => skip(-1),
      nexttrack: () => skip(1),
      stop: () => stop(),
    }
    for (const [name, fn] of Object.entries(handlers)) {
      try {
        navigator.mediaSession.setActionHandler(name, fn)
      } catch {
        // Not every action is supported on every platform; an unsupported one throws and the
        // rest still register.
      }
    }
    return () => {
      for (const name of Object.keys(handlers)) {
        try {
          navigator.mediaSession.setActionHandler(name, null)
        } catch {
          // As above.
        }
      }
    }
  }, [toggle, skip, stop])

  const value = {
    queue,
    at,
    item,
    playing,
    rate,
    time,
    duration,
    failed,
    // The live cue, or null. Consumers compare `itemId` before highlighting so a stale cue from a
    // previous segment never marks up the wrong paragraph.
    cue: cue >= 0 && cues[cue] ? { ...cues[cue], itemId: item?.id } : null,
    start,
    toggle,
    skip,
    stop,
    setRate,
    seek,
  }

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>
}

// ------------------------------------------------------------------ rendering helpers

// One block of printed text, with the word currently being spoken wrapped in a <mark>.
// When nothing is playing this renders the plain string, so the markup only exists while it means
// something - a page full of empty spans is worse for a screen reader, not better.
export function Spoken({ text, itemId, block }) {
  const audio = useAudio()
  const c = audio?.cue
  if (!c || c.itemId !== itemId || c.block !== block) return text
  return (
    <>
      {text.slice(0, c.from)}
      <mark className="spoken-word">{text.slice(c.from, c.to)}</mark>
      {text.slice(c.to)}
    </>
  )
}

// ------------------------------------------------------------------ transport

const fmt = (s) => {
  if (!Number.isFinite(s)) return '0:00'
  const m = Math.floor(s / 60)
  return `${m}:${String(Math.floor(s % 60)).padStart(2, '0')}`
}

export function AudioBar() {
  const a = useAudio()
  const [t] = useT()
  if (!a?.queue) return null
  const { queue, at, playing, rate, time, duration, failed } = a

  // "134" is what a screen reader reads from a range whose value is seconds, which tells nobody
  // anything. Spelled out, and singular and plural are separate keys rather than a naive "1
  // minutes" — this is the one string in the app a blind visitor depends on to scrub.
  const spoken = (s) => {
    if (!Number.isFinite(s)) return t('ui.audioSeconds', { n: 0 })
    const m = Math.floor(s / 60)
    const sec = Math.floor(s % 60)
    const mPart = m ? t(m === 1 ? 'ui.audioMinute' : 'ui.audioMinutes', { n: m }) : ''
    const sPart = t(sec === 1 ? 'ui.audioSecond' : 'ui.audioSeconds', { n: sec })
    return m ? `${mPart} ${sPart}` : sPart
  }

  return (
    <div className="audio-bar" role="region" aria-label={t('ui.audioGuide')}>
      {/* A real slider rather than the read-only bar this used to be. Native input[type=range]
          because it arrives with role="slider", the arrow/Home/End keys and drag-free keyboard
          operation already correct — SC 2.5.7 requires that a drag is never the only way. */}
      <label className="audio-seek">
        <span className="visually-hidden">{t('ui.audioPosition')}</span>
        <input
          type="range"
          min="0"
          max={Number.isFinite(duration) && duration > 0 ? duration : 0}
          step="0.5"
          value={Math.min(time, duration || 0)}
          onChange={(e) => a.seek(Number(e.target.value))}
          aria-valuetext={t('ui.audioElapsed', { elapsed: spoken(time), total: spoken(duration) })}
          disabled={!duration}
        />
      </label>

      <div className="audio-row">
        <div className="audio-what">
          <strong>{queue.title}</strong>
          {/* Announced politely so a screen-reader user hears the section change without having
              the narration itself interrupted. */}
          {/* The first item of a group tour is the panel, whose label is the group title — so
              without this the bar printed the same sentence twice, once above the other. */}
          <span aria-live="polite">
            {queue.items[at]?.label && queue.items[at].label !== queue.title
              ? `${queue.items[at].label} · ${t('ui.audioSection', { n: at + 1, total: queue.items.length })}`
              : t('ui.audioSection', { n: at + 1, total: queue.items.length })}
          </span>
        </div>

        <div className="audio-controls">
          <button type="button" onClick={() => a.skip(-1)} disabled={at === 0} aria-label={t('ui.audioPrevious')}>
            <span aria-hidden="true">⏮</span>
          </button>
          <button
            type="button"
            className="audio-play"
            onClick={a.toggle}
            aria-label={playing ? t('ui.audioPause') : t('ui.audioPlay')}
          >
            <span aria-hidden="true">{playing ? '⏸' : '▶'}</span>
          </button>
          <button
            type="button"
            onClick={() => a.skip(1)}
            disabled={at + 1 >= queue.items.length}
            aria-label={t('ui.audioNext')}
          >
            <span aria-hidden="true">⏭</span>
          </button>

          <label className="audio-rate">
            <span className="visually-hidden">{t('ui.audioSpeed')}</span>
            <select value={rate} onChange={(e) => a.setRate(Number(e.target.value))}>
              {RATES.map((r) => (
                <option key={r} value={r}>
                  {r}×
                </option>
              ))}
            </select>
          </label>

          <span className="audio-time">
            {fmt(time)} / {fmt(duration)}
          </span>

          <button type="button" onClick={a.stop} aria-label={t('ui.audioStop')}>
            <span aria-hidden="true">✕</span>
          </button>
        </div>
      </div>

      {failed && <p className="audio-failed">{t('ui.audioFailed')}</p>}
    </div>
  )
}
