// Playback for the generated narration, per BUILD-SPEC-v2.md §13.
//
// The audio is 552 files, one per printed block, generated by scripts/audio.mjs. That shape is
// what makes this component simple: a section is a file, so "skip this section" is "play the next
// file" and there is no seeking, no chapter table, and nothing that can drift out of sync.
//
// What §13 asks for and where it lives here:
//   - two tracks, description then interpretation. Only interpretation exists as content, so only
//     interpretation plays. See docs/audio-generation.md for what was cut and why.
//   - variable speed 0.5x-2x, pitch preserved. RATES below; preservesPitch is set on the element.
//   - plays across navigation. The element is created once, outside React's tree, and the provider
//     sits above the router - so changing page does not interrupt the narration.
//   - cues map one-to-one onto printed segments, generated at production time. We only read them.

import { createContext, useCallback, useContext, useEffect, useRef, useState } from 'react'
import { PauseIcon, PlayIcon, SkipBackIcon, SkipForwardIcon, XIcon } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Slider } from '@/components/ui/slider'
import { index } from './collection.js'
import { useT } from './lang.jsx'
import { useA11y } from './a11y.jsx'

// Where each language's narration is served from, written by scripts/split.mjs from the audio
// index. Two things follow from it being data rather than a constant.
//
// A queue item carries the language its TEXT actually resolved to, not the language the visitor
// selected — the same rule §7 applies to lang and dir. A German page with two segments still in
// English plays two English files, which is correct: §13 requires the spoken words to be the
// printed words, and at that point the printed words are English.
//
// And moving audio off the repo later is a change to `base` in a JSON file rather than to this
// player. English alone is 44MB.
const AUDIO = index.audio ?? {}
// Availability is per SEGMENT, not per language. German is why: its pack translates every story,
// so on a German page every item resolves to 'de' — but its narration is a four-file pilot
// covering one object. A per-language answer offered every German visitor an audio guide that was
// dead on arrival; the set answers for the file the player would actually request.
const VOICED = Object.fromEntries(Object.entries(AUDIO).map(([code, a]) => [code, new Set(a.segments)]))
export const hasAudio = (lang, id) => !!VOICED[lang]?.has(id)
const baseFor = (lang) => AUDIO[lang]?.base ?? `/audio/${lang}`
export const RATES = [0.5, 0.75, 1, 1.25, 1.5, 2]

// The printed blocks of one segment, built exactly the way scripts/audio.mjs builds them. If these
// two ever disagree the cue text stops lining up with the words on screen, so the construction is
// deliberately identical rather than merely similar.
export const blocksOf = (heading, text) =>
  [heading, ...String(text ?? '').split(/\n{2,}/)].map((b) => (b ?? '').trim()).filter(Boolean)

// ------------------------------------------------------------------ cues

const toSeconds = (t) => {
  const [h, m, s] = t.split(':')
  return Number(h) * 3600 + Number(m) * 60 + Number(s)
}

function parseVtt(text) {
  const out = []
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(/^(\d\d:\d\d:\d\d\.\d\d\d) --> (\d\d:\d\d:\d\d\.\d\d\d)/)
    if (!m) continue
    const body = (lines[i + 1] ?? '').trim()
    if (body) out.push({ start: toSeconds(m[1]), end: toSeconds(m[2]), text: body })
  }
  return out
}

// Turn each cue into a character range inside one of the printed blocks, so the page can highlight
// the actual rendered text rather than a copy of it.
//
// This walks forwards and never searches backwards: the narration reads the blocks in order, so a
// cue is always at or after the previous one. That matters for repeated words - highlighting the
// first "the" in a paragraph every time the voice says "the" would look broken, and a naive
// indexOf from zero would do exactly that.

// One kind of cue is damaged rather than genuinely mismatched. buildVtt in scripts/audio.mjs
// folds Azure's punctuation-only word events into the word before them, and the fold used to keep
// no space — so a spaced dash arrived as "hydroids—" while the page prints "hydroids —". The fold
// now reads the separator from the printed text, but 18 English VTTs shipped in the old shape and
// stay as they are, because regenerating audio costs money. This rebuilds such a cue as a pattern
// that permits whitespace ahead of punctuation, which recovers exactly that damage and nothing
// else: a cue that matches verbatim never gets here, and the range it yields covers the printed
// word and its dash together.
const reflowed = (needle) => {
  let src = ''
  for (const [i, ch] of [...needle].entries()) {
    if (i && !/[\s\p{L}\p{N}]/u.test(ch)) src += '\\s?'
    src += ch.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  }
  return new RegExp(src, 'gu')
}

function alignCues(cues, blocks) {
  const out = []
  let b = 0
  let pos = 0
  for (const cue of cues) {
    const needle = cue.text.trim()
    if (!needle) continue
    let placed = false
    while (b < blocks.length) {
      let at = blocks[b].indexOf(needle, pos)
      let len = needle.length
      if (at === -1) {
        const re = reflowed(needle)
        re.lastIndex = pos
        const m = re.exec(blocks[b])
        if (m) {
          at = m.index
          len = m[0].length
        }
      }
      if (at !== -1) {
        out.push({ ...cue, block: b, from: at, to: at + len })
        pos = at + len
        placed = true
        break
      }
      b++
      pos = 0
    }
    // A cue we cannot place means the text on screen is not the text that was voiced. Rather than
    // highlight the wrong words, stop aligning and let the rest play without a highlight.
    if (!placed) break
  }
  return out
}

// ------------------------------------------------------------------ provider

const Ctx = createContext(null)
export const useAudio = () => useContext(Ctx)

export function AudioProvider({ children }) {
  const el = useRef(null)
  if (el.current === null && typeof Audio !== 'undefined') {
    el.current = new Audio()
    el.current.preload = 'none'
  }

  // queue: { key, title, items: [{ id, label, blocks }] }. key identifies what is playing so a
  // second press on the same thing toggles rather than restarts.
  const [queue, setQueue] = useState(null)
  const [at, setAt] = useState(0)
  const [playing, setPlaying] = useState(false)
  const [rate, setRateRaw] = useState(1)
  const [cues, setCues] = useState([])
  const [cue, setCue] = useState(-1)
  const [time, setTime] = useState(0)
  const [duration, setDuration] = useState(0)
  const [failed, setFailed] = useState(false)

  // Read-along only works if the highlighted word is on screen, and until now nothing kept it
  // there — the narration ran on while the visitor sat looking at a paragraph it had left. On by
  // default because following the words is the whole point of §13's one-to-one cue mapping;
  // switchable, because auto-scroll fights anyone who wants to read ahead or back. The switch is
  // in Display settings (§18) rather than the player: it is a preference, and it should persist.
  const { prefs } = useA11y()
  const follow = prefs.followWords
  const [t] = useT()

  // How long the visitor keeps the scroll after taking it over.
  //
  // Modelled on a car's navigation map: pan away and it leaves you alone, then re-centres once you
  // stop touching it or once the car moves, because what it is following has moved on. Both
  // triggers, for the same reasons.
  //
  // 8s rather than the 4s first sketched. Measured, the narration crosses a paragraph every 6
  // seconds, so a 4s timer expires inside an ordinary read-along pause — reading is
  // indistinguishable from idling, and the resume would land while the visitor was most absorbed.
  // 8s clears a paragraph with room to spare. One constant; retune here.
  const IDLE_MS = 8000
  // The "car has started moving" trigger: the guide has reached a new section, so whatever they
  // scrolled off to look at is no longer the subject.
  //
  // 4s, not the 1.5s this started at. Sections here are 7 to 30 seconds, so a new one very often
  // begins moments after a swipe: measured, it took the page back 1,530ms after the visitor moved
  // it, which is the snatching this whole change exists to stop. Four seconds is long enough to
  // have looked at the thing you scrolled to — and it lands where the original instinct did, so
  // the rule reads as "4 seconds, if the guide has moved on; 8 if it has not".
  const SECTION_SETTLE_MS = 4000
  // A smooth scroll takes a few hundred ms, during which the mark is still measurably out of place.
  // Without this the next cue reads that as a fresh miss and scrolls again, compounding.
  const SCROLL_SETTLE_MS = 400

  const takenOver = useRef(null)
  const scrolledAt = useRef(0)
  const atRef = useRef(0)
  atRef.current = at

  const item = queue?.items[at] ?? null

  // Load the segment whenever the queue or position changes. `wanted` guards against a fast
  // sequence of skips resolving out of order and leaving stale cues on screen.
  useEffect(() => {
    const audio = el.current
    if (!audio || !item) return
    let wanted = true
    setCues([])
    setCue(-1)
    setFailed(false)
    // The item's own language, not the session's: a block that fell back to English is played from
    // the English narration, because that is what is printed at that point on the page.
    const base = baseFor(item.lang ?? 'en')
    audio.src = `${base}/${item.id}.mp3`
    audio.playbackRate = rate
    audio.preservesPitch = true
    if (playing) audio.play().catch(() => setFailed(true))

    fetch(`${base}/${item.id}.vtt`)
      .then((r) => (r.ok ? r.text() : Promise.reject(new Error(String(r.status)))))
      .then((text) => {
        if (wanted) setCues(alignCues(parseVtt(text), item.blocks))
      })
      // No cues is a degraded but working player: audio plays, nothing highlights.
      .catch(() => {})

    return () => {
      wanted = false
    }
    // `queue?.key` is a dependency because queues share item ids by design — a group tour and an
    // object's own queue name the same sections with the same strings. Keyed on the id alone,
    // switching queues onto an identical first item never re-ran this effect, so nothing called
    // play(): the bar claimed to be playing while the element sat paused. A queue switch reloads
    // the section instead, which also honours what the press meant — play this from the start.
    // `playing` and `rate` are deliberately not dependencies - they are applied here on load and
    // maintained by the effects below. Including them would reload the file on every speed change.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [queue?.key, item?.id])

  useEffect(() => {
    const audio = el.current
    if (!audio) return
    audio.playbackRate = rate
    audio.preservesPitch = true
  }, [rate])

  // Follow the playhead on animation frames rather than the element's timeupdate event, which
  // fires about four times a second - fine for a progress bar, visibly late for a word.
  useEffect(() => {
    const audio = el.current
    if (!audio || !playing) return
    let raf = 0
    const tick = () => {
      const now = audio.currentTime
      setTime(now)
      setCue((prev) => {
        if (cues[prev] && now >= cues[prev].start && now < cues[prev].end) return prev
        const next = cues.findIndex((c) => now >= c.start && now < c.end)
        return next
      })
      raf = requestAnimationFrame(tick)
    }
    raf = requestAnimationFrame(tick)
    return () => cancelAnimationFrame(raf)
  }, [playing, cues])

  useEffect(() => {
    const audio = el.current
    if (!audio) return
    const onEnd = () => {
      setAt((i) => {
        if (!queue || i + 1 >= queue.items.length) {
          setPlaying(false)
          return i
        }
        return i + 1
      })
    }
    const onMeta = () => setDuration(audio.duration || 0)
    const onErr = () => setFailed(true)
    audio.addEventListener('ended', onEnd)
    audio.addEventListener('loadedmetadata', onMeta)
    audio.addEventListener('error', onErr)
    return () => {
      audio.removeEventListener('ended', onEnd)
      audio.removeEventListener('loadedmetadata', onMeta)
      audio.removeEventListener('error', onErr)
    }
  }, [queue])

  const start = useCallback(
    (next, from = 0) => {
      const audio = el.current
      if (!audio) return
      // Pressing Listen, or skipping, is a request to be taken to the words — so it ends any
      // exploring rather than waiting out the timer.
      takenOver.current = null
      if (queue?.key === next.key) {
        // Same thing already loaded: treat the press as play/pause.
        if (playing) {
          audio.pause()
          setPlaying(false)
        } else {
          audio.play().catch(() => setFailed(true))
          setPlaying(true)
        }
        return
      }
      setQueue(next)
      setAt(from)
      setPlaying(true)
    },
    [queue, playing]
  )

  const toggle = useCallback(() => {
    const audio = el.current
    if (!audio || !queue) return
    if (playing) {
      audio.pause()
      setPlaying(false)
    } else {
      audio.play().catch(() => setFailed(true))
      setPlaying(true)
    }
  }, [queue, playing])

  // §13's skip. Because a section is a file, this is just "load the next one" - it cannot land in
  // the wrong place the way a seek into a long file can.
  //
  // At the ends it does nothing at all. The on-screen buttons are disabled there, but a lock
  // screen's next-track button is not: clamping the index and then asserting `playing` turned
  // that press into a phone that says "playing" over a paused element.
  const skip = useCallback(
    (delta) => {
      if (!queue) return
      const next = Math.min(queue.items.length - 1, Math.max(0, atRef.current + delta))
      if (next === atRef.current) return
      takenOver.current = null
      setAt(next)
      setPlaying(true)
    },
    [queue]
  )

  const stop = useCallback(() => {
    const audio = el.current
    if (audio) {
      audio.pause()
      audio.removeAttribute('src')
      audio.load()
    }
    setQueue(null)
    setPlaying(false)
    setCues([])
    setCue(-1)
  }, [])

  const setRate = useCallback((r) => setRateRaw(r), [])

  const seek = useCallback((seconds) => {
    const audio = el.current
    if (!audio || !Number.isFinite(seconds)) return
    audio.currentTime = seconds
    setTime(seconds)
  }, [])

  // A swipe, a wheel turn or a scroll key means the visitor is driving now.
  //
  // Deliberately not the `scroll` event. Our own smooth scrolling fires a stream of those, so a
  // feature listening for them mistakes itself for the user, hands over control it was never
  // asked for, and never takes it back. wheel, touch and the scroll keys are things only a person
  // does. Anything inside the transport bar is excluded: dragging the seek slider or pressing skip
  // is operating the guide, not exploring the page, and should not stop it following.
  useEffect(() => {
    const KEYS = new Set(['ArrowUp', 'ArrowDown', 'PageUp', 'PageDown', 'Home', 'End', ' ', 'Spacebar'])
    const inTransport = (e) => e.target instanceof Node && !!document.querySelector('.audio-bar')?.contains(e.target)
    const took = (e) => {
      if (inTransport(e)) return
      takenOver.current = { time: performance.now(), section: atRef.current }
    }
    const onKey = (e) => {
      if (KEYS.has(e.key)) took(e)
    }
    addEventListener('wheel', took, { passive: true })
    addEventListener('touchstart', took, { passive: true })
    addEventListener('touchmove', took, { passive: true })
    addEventListener('keydown', onKey)
    return () => {
      removeEventListener('wheel', took)
      removeEventListener('touchstart', took)
      removeEventListener('touchmove', took)
      removeEventListener('keydown', onKey)
    }
  }, [])

  // Keep the spoken word on screen. Runs after the cue has rendered, so the <mark> exists.
  useEffect(() => {
    if (!follow || !playing) return
    const mark = document.querySelector('.spoken-word')
    if (!mark) return

    const now = performance.now()
    if (now - scrolledAt.current < SCROLL_SETTLE_MS) return

    // While the visitor has the scroll, leave it entirely alone.
    const over = takenOver.current
    let resuming = false
    if (over) {
      const idle = now - over.time
      const sectionMoved = at !== over.section
      if (idle < IDLE_MS && !(sectionMoved && idle > SECTION_SETTLE_MS)) return
      takenOver.current = null
      resuming = true
    }

    const bar = document.querySelector('.audio-bar')?.getBoundingClientRect().height ?? 0
    // The readable band: clear of the masthead above, clear of the transport bar below.
    const top = 72
    const bottom = innerHeight - bar - 24
    const r = mark.getBoundingClientRect()

    // §18 asks for prefers-reduced-motion on every transition. A smooth scroll that repeats for
    // 137 minutes is exactly what that setting is for.
    const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches
    const behavior = reduced ? 'auto' : 'smooth'

    // Coming back from exploring is the one move that should be a placement rather than a nudge.
    // The visitor has been away, the words are somewhere else entirely, and putting them where
    // reading starts is the whole point — a third of the way down the band.
    //
    // Tried and rejected: doing the same at every section change, on the theory that a new object
    // deserves a proper entrance. It made things worse, and measurably — over two minutes it took
    // the median move from 110px to 438px and put four moves of the eight over half a screen. A
    // new heading arriving low and then easing up is gentler than the page leaping to meet it.
    if (resuming) {
      scrolledAt.current = now
      const back = r.top - (top + (bottom - top) * 0.35)
      // Someone who wandered a long way gets taken back instantly rather than flown there. Smoothly
      // animating thousands of pixels — 5,748 of them in one test — is a long blur that shows the
      // visitor nothing and delays the words they are already hearing. Under a couple of screens it
      // is a movement worth watching, because it tells them where they went.
      scrollBy({ top: back, behavior: Math.abs(back) > innerHeight * 2 ? 'auto' : behavior })
      return
    }

    // Only the floor is enforced, not the ceiling. Above is a fine place for the spoken word to be
    // — there is a screenful of what comes next below it — and correcting upwards mostly fired at
    // the top of a page, where the scroll is already at zero and the move does nothing: three
    // futile scrolls in the first two minutes of a tour, before this.
    if (r.bottom <= bottom) return

    // The old rule scrolled the word to the dead centre of the screen however far it had drifted,
    // so the correction bore no relation to the error: measured on a 390px phone, a median move of
    // 331px and a worst of 594px — 39% and 70% of the screen — arriving about once every 14
    // seconds. Rare and violent, which is what read as aggressive.
    //
    // Instead, move by the least that puts the word back inside the band with a few lines of room
    // to spare. Three lines is the tuning: park it hard against the edge and the very next line
    // triggers another scroll, giving a constant crawl; park it in the middle and we are back to
    // leaping. Three lines is one small step every few lines, which reads as the page keeping up
    // rather than snatching.
    const line = parseFloat(getComputedStyle(mark.parentElement ?? mark).lineHeight) || 24
    scrolledAt.current = now
    scrollBy({ top: r.bottom - (bottom - line * 3), behavior })
  }, [cue, at, follow, playing])

  // Lock screen, headphone buttons, car displays. A visitor walking a gallery with the phone in a
  // pocket is the case §13's "plays across navigation" is really about, and without this the only
  // way to pause is to take the phone out and find the bar.
  useEffect(() => {
    if (!('mediaSession' in navigator)) return
    if (!queue || !item) {
      navigator.mediaSession.metadata = null
      navigator.mediaSession.playbackState = 'none'
      return
    }
    navigator.mediaSession.metadata = new MediaMetadata({
      title: item.label,
      // For a single object the queue title and the first item's label are the same string, and a
      // lock screen showing the same words twice reads as a bug.
      artist: queue.title === item.label ? t('ui.collectionTitle') : queue.title,
      album: 'Canterbury Museum',
    })
    navigator.mediaSession.playbackState = playing ? 'playing' : 'paused'
  }, [queue, item, playing, t])

  useEffect(() => {
    if (!('mediaSession' in navigator)) return
    const handlers = {
      play: () => toggle(),
      pause: () => toggle(),
      previoustrack: () => skip(-1),
      nexttrack: () => skip(1),
      stop: () => stop(),
    }
    for (const [name, fn] of Object.entries(handlers)) {
      try {
        navigator.mediaSession.setActionHandler(name, fn)
      } catch {
        // Not every action is supported on every platform; an unsupported one throws and the
        // rest still register.
      }
    }
    return () => {
      for (const name of Object.keys(handlers)) {
        try {
          navigator.mediaSession.setActionHandler(name, null)
        } catch {
          // As above.
        }
      }
    }
  }, [toggle, skip, stop])

  const value = {
    queue,
    at,
    item,
    playing,
    rate,
    time,
    duration,
    failed,
    // The live cue, or null. Consumers compare `itemId` before highlighting so a stale cue from a
    // previous segment never marks up the wrong paragraph.
    cue: cue >= 0 && cues[cue] ? { ...cues[cue], itemId: item?.id } : null,
    start,
    toggle,
    skip,
    stop,
    setRate,
    seek,
  }

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>
}

// ------------------------------------------------------------------ rendering helpers

// One block of printed text, with the word currently being spoken wrapped in a <mark>.
// When nothing is playing this renders the plain string, so the markup only exists while it means
// something - a page full of empty spans is worse for a screen reader, not better.
// `offset` is where this run of text starts inside its block, and it exists so a block can be
// broken up — to put a link inside a sentence, say — without the read-along losing its place. The
// cue's from/to are offsets into the whole block, so a run that starts partway through subtracts
// its own start and clamps to its own length. Left at 0 the behaviour is unchanged.
export function Spoken({ text, itemId, block, offset = 0 }) {
  const audio = useAudio()
  const c = audio?.cue
  if (!c || c.itemId !== itemId || c.block !== block) return text
  const from = Math.max(0, Math.min(text.length, c.from - offset))
  const to = Math.max(0, Math.min(text.length, c.to - offset))
  if (from >= to) return text
  return (
    <>
      {text.slice(0, from)}
      <mark className="spoken-word">{text.slice(from, to)}</mark>
      {text.slice(to)}
    </>
  )
}

// ------------------------------------------------------------------ transport

const fmt = (s) => {
  if (!Number.isFinite(s)) return '0:00'
  const m = Math.floor(s / 60)
  return `${m}:${String(Math.floor(s % 60)).padStart(2, '0')}`
}

export function AudioBar() {
  const a = useAudio()
  const [t] = useT()
  if (!a?.queue) return null
  const { queue, at, playing, rate, time, duration, failed } = a

  // "134" is what a screen reader reads from a range whose value is seconds, which tells nobody
  // anything. Spelled out, and singular and plural are separate keys rather than a naive "1
  // minutes" — this is the one string in the app a blind visitor depends on to scrub.
  const spoken = (s) => {
    if (!Number.isFinite(s)) return t('ui.audioSeconds', { n: 0 })
    const m = Math.floor(s / 60)
    const sec = Math.floor(s % 60)
    const mPart = m ? t(m === 1 ? 'ui.audioMinute' : 'ui.audioMinutes', { n: m }) : ''
    const sPart = t(sec === 1 ? 'ui.audioSecond' : 'ui.audioSeconds', { n: sec })
    return m ? `${mPart} ${sPart}` : sPart
  }

  return (
    <div className="audio-bar" role="region" aria-label={t('ui.audioGuide')}>
      {/* shadcn's Slider, not its Progress. Progress is a read-out — role="progressbar", no
          keyboard, nothing to grab — and this control has to be seekable, so Progress would have
          silently removed the ability to move through a 137-minute guide. Slider is the seekable
          one, and it keeps what the native range gave us: role="slider", arrow/Home/End keys, and
          therefore no drag-only interaction, which is what SC 2.5.7 requires. */}
      <div className="audio-seek">
        <span className="visually-hidden" id="audio-seek-label">
          {t('ui.audioPosition')}
        </span>
        <Slider
          aria-labelledby="audio-seek-label"
          min={0}
          max={Number.isFinite(duration) && duration > 0 ? duration : 0}
          step={0.5}
          value={[Math.min(time, duration || 0)]}
          onValueChange={(v) => a.seek(Array.isArray(v) ? v[0] : v)}
          getAriaValueText={() => t('ui.audioElapsed', { elapsed: spoken(time), total: spoken(duration) })}
          disabled={!duration}
        />
      </div>

      <div className="audio-row">
        <div className="audio-what">
          <strong>{queue.title}</strong>
          {/* Announced politely so a screen-reader user hears the section change without having
              the narration itself interrupted. */}
          {/* The first item of a group tour is the panel, whose label is the group title — so
              without this the bar printed the same sentence twice, once above the other. */}
          <span aria-live="polite">
            {queue.items[at]?.label && queue.items[at].label !== queue.title
              ? `${queue.items[at].label} · ${t('ui.audioSection', { n: at + 1, total: queue.items.length })}`
              : t('ui.audioSection', { n: at + 1, total: queue.items.length })}
          </span>
        </div>

        <div className="audio-controls">
          {/* Not mirrored under dir="rtl", unlike the back and prev/next arrows. These point along
              the recording rather than along the reading, and a tape does not run the other way for
              an Arabic listener. Matches the convention every other player follows. */}
          <Button variant="bare" size="icon-touch" onClick={() => a.skip(-1)} disabled={at === 0} aria-label={t('ui.audioPrevious')}>
            <SkipBackIcon aria-hidden="true" focusable="false" />
          </Button>
          <Button
            variant="bare"
            size="icon-touch"
            className="audio-play"
            onClick={a.toggle}
            aria-label={playing ? t('ui.audioPause') : t('ui.audioPlay')}
          >
            {playing
              ? <PauseIcon aria-hidden="true" focusable="false" />
              : <PlayIcon aria-hidden="true" focusable="false" />}
          </Button>
          <Button
            variant="bare"
            size="icon-touch"
            onClick={() => a.skip(1)}
            disabled={at + 1 >= queue.items.length}
            aria-label={t('ui.audioNext')}
          >
            <SkipForwardIcon aria-hidden="true" focusable="false" />
          </Button>

          {/* The last native control in the bar, and it sat beside five shadcn ones. Values are
              strings because a Select compares them by identity and RATES are numbers; they go
              back through Number() on the way out. A div rather than a label, for the reason the
              language picker changed: a label may only wrap a form control, and the trigger is a
              button. */}
          <div className="audio-rate">
            <span className="visually-hidden" id="audio-rate-label">
              {t('ui.audioSpeed')}
            </span>
            <Select
              value={String(rate)}
              onValueChange={(v) => v && a.setRate(Number(v))}
              items={RATES.map((r) => ({ value: String(r), label: `${r}×` }))}
            >
              <SelectTrigger className="audio-rate-trigger min-h-11" size="touch" aria-labelledby="audio-rate-label">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {RATES.map((r) => (
                  <SelectItem key={r} value={String(r)}>
                    {r}×
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <span className="audio-time">
            {fmt(time)} / {fmt(duration)}
          </span>

          <Button variant="bare" size="icon-touch" onClick={a.stop} aria-label={t('ui.audioStop')}>
            <XIcon aria-hidden="true" focusable="false" />
          </Button>
        </div>
      </div>

      {failed && <p className="audio-failed">{t('ui.audioFailed')}</p>}
    </div>
  )
}
