// Playback for the generated narration, per BUILD-SPEC-v2.md §13.
//
// The audio is 552 files, one per printed block, generated by scripts/audio.mjs. That shape is
// what makes this component simple: a section is a file, so "skip this section" is "play the next
// file" and there is no seeking, no chapter table, and nothing that can drift out of sync.
//
// What §13 asks for and where it lives here:
//   - two tracks, description then interpretation. Only interpretation exists as content, so only
//     interpretation plays. See docs/audio-generation.md for what was cut and why.
//   - variable speed 0.5x-2x, pitch preserved. RATES below; preservesPitch is set on the element.
//   - plays across navigation. The element is created once, outside React's tree, and the provider
//     sits above the router - so changing page does not interrupt the narration.
//   - cues map one-to-one onto printed segments, generated at production time. We only read them.

import { createContext, useCallback, useContext, useEffect, useRef, useState } from 'react'

const BASE = '/audio/en'
export const RATES = [0.5, 0.75, 1, 1.25, 1.5, 2]

// The printed blocks of one segment, built exactly the way scripts/audio.mjs builds them. If these
// two ever disagree the cue text stops lining up with the words on screen, so the construction is
// deliberately identical rather than merely similar.
export const blocksOf = (heading, text) =>
  [heading, ...String(text ?? '').split(/\n{2,}/)].map((b) => (b ?? '').trim()).filter(Boolean)

// ------------------------------------------------------------------ cues

const toSeconds = (t) => {
  const [h, m, s] = t.split(':')
  return Number(h) * 3600 + Number(m) * 60 + Number(s)
}

function parseVtt(text) {
  const out = []
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(/^(\d\d:\d\d:\d\d\.\d\d\d) --> (\d\d:\d\d:\d\d\.\d\d\d)/)
    if (!m) continue
    const body = (lines[i + 1] ?? '').trim()
    if (body) out.push({ start: toSeconds(m[1]), end: toSeconds(m[2]), text: body })
  }
  return out
}

// Turn each cue into a character range inside one of the printed blocks, so the page can highlight
// the actual rendered text rather than a copy of it.
//
// This walks forwards and never searches backwards: the narration reads the blocks in order, so a
// cue is always at or after the previous one. That matters for repeated words - highlighting the
// first "the" in a paragraph every time the voice says "the" would look broken, and a naive
// indexOf from zero would do exactly that.
function alignCues(cues, blocks) {
  const out = []
  let b = 0
  let pos = 0
  for (const cue of cues) {
    const needle = cue.text.trim()
    if (!needle) continue
    let placed = false
    while (b < blocks.length) {
      const at = blocks[b].indexOf(needle, pos)
      if (at !== -1) {
        out.push({ ...cue, block: b, from: at, to: at + needle.length })
        pos = at + needle.length
        placed = true
        break
      }
      b++
      pos = 0
    }
    // A cue we cannot place means the text on screen is not the text that was voiced. Rather than
    // highlight the wrong words, stop aligning and let the rest play without a highlight.
    if (!placed) break
  }
  return out
}

// ------------------------------------------------------------------ provider

const Ctx = createContext(null)
export const useAudio = () => useContext(Ctx)

export function AudioProvider({ children }) {
  const el = useRef(null)
  if (el.current === null && typeof Audio !== 'undefined') {
    el.current = new Audio()
    el.current.preload = 'none'
  }

  // queue: { key, title, items: [{ id, label, blocks }] }. key identifies what is playing so a
  // second press on the same thing toggles rather than restarts.
  const [queue, setQueue] = useState(null)
  const [at, setAt] = useState(0)
  const [playing, setPlaying] = useState(false)
  const [rate, setRateRaw] = useState(1)
  const [cues, setCues] = useState([])
  const [cue, setCue] = useState(-1)
  const [time, setTime] = useState(0)
  const [duration, setDuration] = useState(0)
  const [failed, setFailed] = useState(false)

  const item = queue?.items[at] ?? null

  // Load the segment whenever the queue or position changes. `wanted` guards against a fast
  // sequence of skips resolving out of order and leaving stale cues on screen.
  useEffect(() => {
    const audio = el.current
    if (!audio || !item) return
    let wanted = true
    setCues([])
    setCue(-1)
    setFailed(false)
    audio.src = `${BASE}/${item.id}.mp3`
    audio.playbackRate = rate
    audio.preservesPitch = true
    if (playing) audio.play().catch(() => setFailed(true))

    fetch(`${BASE}/${item.id}.vtt`)
      .then((r) => (r.ok ? r.text() : Promise.reject(new Error(String(r.status)))))
      .then((text) => {
        if (wanted) setCues(alignCues(parseVtt(text), item.blocks))
      })
      // No cues is a degraded but working player: audio plays, nothing highlights.
      .catch(() => {})

    return () => {
      wanted = false
    }
    // `playing` and `rate` are deliberately not dependencies - they are applied here on load and
    // maintained by the effects below. Including them would reload the file on every speed change.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [item?.id])

  useEffect(() => {
    const audio = el.current
    if (!audio) return
    audio.playbackRate = rate
    audio.preservesPitch = true
  }, [rate])

  // Follow the playhead on animation frames rather than the element's timeupdate event, which
  // fires about four times a second - fine for a progress bar, visibly late for a word.
  useEffect(() => {
    const audio = el.current
    if (!audio || !playing) return
    let raf = 0
    const tick = () => {
      const now = audio.currentTime
      setTime(now)
      setCue((prev) => {
        if (cues[prev] && now >= cues[prev].start && now < cues[prev].end) return prev
        const next = cues.findIndex((c) => now >= c.start && now < c.end)
        return next
      })
      raf = requestAnimationFrame(tick)
    }
    raf = requestAnimationFrame(tick)
    return () => cancelAnimationFrame(raf)
  }, [playing, cues])

  useEffect(() => {
    const audio = el.current
    if (!audio) return
    const onEnd = () => {
      setAt((i) => {
        if (!queue || i + 1 >= queue.items.length) {
          setPlaying(false)
          return i
        }
        return i + 1
      })
    }
    const onMeta = () => setDuration(audio.duration || 0)
    const onErr = () => setFailed(true)
    audio.addEventListener('ended', onEnd)
    audio.addEventListener('loadedmetadata', onMeta)
    audio.addEventListener('error', onErr)
    return () => {
      audio.removeEventListener('ended', onEnd)
      audio.removeEventListener('loadedmetadata', onMeta)
      audio.removeEventListener('error', onErr)
    }
  }, [queue])

  const start = useCallback(
    (next, from = 0) => {
      const audio = el.current
      if (!audio) return
      if (queue?.key === next.key) {
        // Same thing already loaded: treat the press as play/pause.
        if (playing) {
          audio.pause()
          setPlaying(false)
        } else {
          audio.play().catch(() => setFailed(true))
          setPlaying(true)
        }
        return
      }
      setQueue(next)
      setAt(from)
      setPlaying(true)
    },
    [queue, playing]
  )

  const toggle = useCallback(() => {
    const audio = el.current
    if (!audio || !queue) return
    if (playing) {
      audio.pause()
      setPlaying(false)
    } else {
      audio.play().catch(() => setFailed(true))
      setPlaying(true)
    }
  }, [queue, playing])

  // §13's skip. Because a section is a file, this is just "load the next one" - it cannot land in
  // the wrong place the way a seek into a long file can.
  const skip = useCallback(
    (delta) => {
      if (!queue) return
      setAt((i) => Math.min(queue.items.length - 1, Math.max(0, i + delta)))
      setPlaying(true)
    },
    [queue]
  )

  const stop = useCallback(() => {
    const audio = el.current
    if (audio) {
      audio.pause()
      audio.removeAttribute('src')
      audio.load()
    }
    setQueue(null)
    setPlaying(false)
    setCues([])
    setCue(-1)
  }, [])

  const setRate = useCallback((r) => setRateRaw(r), [])

  const value = {
    queue,
    at,
    item,
    playing,
    rate,
    time,
    duration,
    failed,
    // The live cue, or null. Consumers compare `itemId` before highlighting so a stale cue from a
    // previous segment never marks up the wrong paragraph.
    cue: cue >= 0 && cues[cue] ? { ...cues[cue], itemId: item?.id } : null,
    start,
    toggle,
    skip,
    stop,
    setRate,
  }

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>
}

// ------------------------------------------------------------------ rendering helpers

// One block of printed text, with the word currently being spoken wrapped in a <mark>.
// When nothing is playing this renders the plain string, so the markup only exists while it means
// something - a page full of empty spans is worse for a screen reader, not better.
export function Spoken({ text, itemId, block }) {
  const audio = useAudio()
  const c = audio?.cue
  if (!c || c.itemId !== itemId || c.block !== block) return text
  return (
    <>
      {text.slice(0, c.from)}
      <mark className="spoken-word">{text.slice(c.from, c.to)}</mark>
      {text.slice(c.to)}
    </>
  )
}

// ------------------------------------------------------------------ transport

const fmt = (s) => {
  if (!Number.isFinite(s)) return '0:00'
  const m = Math.floor(s / 60)
  return `${m}:${String(Math.floor(s % 60)).padStart(2, '0')}`
}

export function AudioBar() {
  const a = useAudio()
  if (!a?.queue) return null
  const { queue, at, playing, rate, time, duration, failed } = a
  const pct = duration ? Math.min(100, (time / duration) * 100) : 0

  return (
    <div className="audio-bar" role="region" aria-label="Audio guide">
      <div className="audio-progress" aria-hidden="true">
        <span style={{ width: `${pct}%` }} />
      </div>

      <div className="audio-row">
        <div className="audio-what">
          <strong>{queue.title}</strong>
          {/* Announced politely so a screen-reader user hears the section change without having
              the narration itself interrupted. */}
          <span aria-live="polite">
            {queue.items[at]?.label} · {at + 1} of {queue.items.length}
          </span>
        </div>

        <div className="audio-controls">
          <button type="button" onClick={() => a.skip(-1)} disabled={at === 0} aria-label="Previous section">
            ⏮
          </button>
          <button type="button" className="audio-play" onClick={a.toggle} aria-label={playing ? 'Pause' : 'Play'}>
            {playing ? '⏸' : '▶'}
          </button>
          <button
            type="button"
            onClick={() => a.skip(1)}
            disabled={at + 1 >= queue.items.length}
            aria-label="Next section"
          >
            ⏭
          </button>

          <label className="audio-rate">
            <span className="visually-hidden">Speed</span>
            <select value={rate} onChange={(e) => a.setRate(Number(e.target.value))}>
              {RATES.map((r) => (
                <option key={r} value={r}>
                  {r}×
                </option>
              ))}
            </select>
          </label>

          <span className="audio-time">
            {fmt(time)} / {fmt(duration)}
          </span>

          <button type="button" onClick={a.stop} aria-label="Stop and close the audio guide">
            ✕
          </button>
        </div>
      </div>

      {failed && <p className="audio-failed">That section would not play.</p>}
    </div>
  )
}
